import { jsPDF } from 'jspdf';

// FREE FEATURE: Export the action plan as a clean PDF, entirely client-side (jsPDF), no server cost.
export function exportNoticeToPdf(notice) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const marginX = 48;
  let y = 60;
  const pageWidth = doc.internal.pageSize.getWidth() - marginX * 2;

  function heading(text, size = 16) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(size);
    doc.setTextColor('#201F52');
    doc.text(text, marginX, y);
    y += size * 1.1;
  }

  function paragraph(text, size = 11) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(size);
    doc.setTextColor('#3A3F52');
    const lines = doc.splitTextToSize(text, pageWidth);
    lines.forEach((line) => {
      if (y > 780) {
        doc.addPage();
        y = 60;
      }
      doc.text(line, marginX, y);
      y += size * 1.4;
    });
    y += 6;
  }

  function bulletList(title, items) {
    if (!items || items.length === 0) return;
    heading(title, 13);
    items.forEach((item) => paragraph(`•  ${item}`));
    y += 4;
  }

  heading(notice.title, 20);
  paragraph(`Generated by Notice2Action on ${new Date().toLocaleDateString()}`, 9);
  y += 6;

  if (notice.summary) bulletList('Summary', [notice.summary]);

  if (notice.deadlines?.length) {
    heading('Deadlines', 13);
    notice.deadlines.forEach((d) =>
      paragraph(`•  ${d.label}: ${d.date || d.rawText || 'Not specified'}`)
    );
    y += 4;
  }

  bulletList('Eligibility', notice.eligibility);
  bulletList('Required Documents', notice.requiredDocuments);
  bulletList('Important Instructions', notice.importantInstructions);

  if (notice.actionChecklist?.length) {
    heading('Action Checklist', 13);
    notice.actionChecklist.forEach((item) =>
      paragraph(`${item.done ? '[x]' : '[ ]'}  ${item.text}`)
    );
    y += 4;
  }

  if (notice.dontMiss) bulletList("Don't Miss This", [notice.dontMiss]);

  doc.save(`${notice.title.replace(/[^a-z0-9]/gi, '_')}.pdf`);
}
